#!/bin/bash

##
# Post-processes .nc files generated by Fusion 360 that are to be consumed by
# GRBL (v0.9).
#
# NB: Gcode should be exported with the following options in Fusion:
#
# - "use G28"        : false
# - "write tools"    : false
# - "write machines" : false
##

# remove `M30` - it seems to cause problems in GRBL
sed -e '/^M30/d' |

# remove the opening and trailing `%` lines
sed -e '/^\%/d'
